openapi: 3.0.0
info:
  version: 1.0.0
  title: 'Borrow API'
  description: 'API for new borrow app'

servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/ALLENLIN_1/Account/1.0.0
  - description: UAT version
    url: https://api.borrow.uat.handypay.com.au/v1
  - description: Prod version
    url: https://api.borrow.handypay.com.au/v1

security:
  - bearerAuth: []         
  
tags:
  - name: Authentication
  - name: User

paths: 
  /login:
    post:
      tags: 
        - Authentication
      description: Log in
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginInfo'
      responses:
        '200':
          description: Successfully logout

  /logout:
    post:
      tags: 
        - Authentication
      description: Log out
      responses:
        '200':
          description: Successfully login
          content:
            application/json:
              schema:
                type: object
                properties:
                  accessToken: 
                    type: string
                    example: eyJhbGciOiJSUzUxMiIsInR5cCI6IkpXVCJ9
                  refreshToken: 
                    type: string
                    example: 37f9e1f487298ae9d47c9f08b231b4729a5f8b11
                  token_type: 
                    type: string
                    example: bearer
        '400':
          description: Invalid username/password supplied

  /user:
    get:
      tags:
        - User
      description: Return account information
      responses:
        '200':
          description: Successfully returned an account information
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserInfo'

        '400':
          description: Invalid request
          
          
components:
  securitySchemes:
    bearerAuth:            # arbitrary name for the security scheme
      type: http
      scheme: bearer
  schemas:
    UserInfo:
      type: object
      required: 
        - firstName
        - mobileNumber
      properties: 
        id:
          type: string
          format: uuid
          example: aE71e000000001dCCC
        firstName:
          type: string
          example: Allen
        lastName:
          type: string
          example: Wu
        mobileNumber:
          type: string
          example: 0412123123
        alternativePhoneNumber:
          type: string
          example: 0412321321
        driversLicenceNumber:
          type: string
          example: 123456789
        licenceState: 
          type: string
          example: NSW
        employerName:
          type: string
          example: Handy Finance
        timeWithEmployer:
          type: string
          example: <1y
        yourEmployerIndustry:
          type: string
          example: Finance Service
        occupation:
          type: string
          example: Engineer
        currentAddress:
          type: string
          example: 201 Miller Street, North Sydney, NSW
        emailAddress:
          type: string
          example: allen.lin@ourmoneymarket.com
        securityQuestionData:
          type: number
          example: 1
        securityAnswer:
          type: string
          example: Luna
    LoginInfo: 
      type: object
      required:
        - username
        - password
        - grantType
      properties:
        username:
          type: string
          example: allen.lin@ourmoneymarket.com
        password:
          type: string
          example: Password!
        grantType:
          type: string
          example: password